// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar"
import Footer from "./components/footer"
import { Montserrat } from "next/font/google";
import { AuthProvider } from "@/context/authContext";
import { Toaster } from "react-hot-toast";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const montserrat = Montserrat({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased min-h-screen flex flex-col bg-black`}
      >
        <AuthProvider>
          <Navbar/>
          {children}
          <Toaster position="top-right" reverseOrder={false}  
          toastOptions={{
            success: {
              style: {
                background: "linear-gradient(90deg, #8b5cf6, #ec4899)", // purple → pink
                color: "#fff",
                fontWeight: "bold",
                textShadow: "0 0 8px #ec4899, 0 0 12px #8b5cf6", // neon glow
                borderRadius: "12px",
                boxShadow: "0 0 20px rgba(236, 72, 153, 0.8)",
              },
              iconTheme: {
                primary: "#ec4899", // pink
                secondary: "#fff", // white icon background
              },
            },
          }}/>
          <Footer/>
        </AuthProvider>
      </body>
    </html>
  );
}
